### ISSUE TITLE
Connecting to Amazon ec2 

### ISSUE THREAD

**Issue by jordanbaucke** [liftoff/GateOne#114]
I have GateOne installed and up and running, I just can't figure out the authentication process.

Im using a Ubuntu 12.04 AMI and the default user and / private key (.pem converted to .ppk, to connect with putty) file I downloaded when I setup the AMI.

I visit my AMIs public DNS, and choose:

Host: ssh://ubuntu@myamidnsaddress:22
Port: 22
user: ubuntu

But at this point I get a invalid key error when I go to connect. I think key-based authentication is supported in the current release, so I just need to figure out how to associate my private key to the session. I tried using the SSH plugin manager but didn't get very far.

Thanks

**Comment by AlienGit** [comment]
Hey Dan... I apologize for opening this 3 years later... but I'm at a loss about what you meant about not using putty key, etc. Is there something with detailed explanation? Thanks!

**Comment by LysanderM** [comment]
Fantastic!! OpenSSH key generation works, thanks.
