### ISSUE TITLE
What is the best way to connect to SSH using Javascript

### ISSUE THREAD

**Issue by tabdulradi** [liftoff/GateOne#147]
Hi, I using Gateone to connect to multiple machines, using SSH,
I want from JavaScript to auto-connect to a ssh url, so that user don't enter the credentials himself.
I've seen the "GateOne.prefs.autoConnectURL", but I want "autoConnectURL" per terminal.

Now I am editing "ssh_connect.py", to be less interactive (doesn't print anything, just waits forever until it receives a valid connection string).
then from Javascript I should call :

``` Javascript
GateOne.ws.send(JSON.stringify({'c': '\u0015ssh://password:username@host:22\n'}));
```

It seems to do the job, but I am wondering if there is something better.

**Comment by pareshgehlot** [comment]
Hello liftoff,

I also want the same functionality, where in user don't need to enter
1. Hostname
2. Port
3. Username
4. Password

All these above information will be receiving from a file, but after receiving those information, I don't know, which are the files and in which folders, I need to update above information, to autoConnect with above credentials.

I am new to GateOne, can you please help me?

Thanks in advance.
