### ISSUE TITLE
can't create server.conf

### ISSUE THREAD

**Issue by justinvj15** [liftoff/GateOne#232]
i have Python 2.7.3 and tornado version 3.0 

i get below when running gateone.py

Traceback (most recent call last):
  File "gateone.py", line 289, in <module>
    tornado.options.enable_pretty_logging()
AttributeError: 'module' object has no attribute 'enable_pretty_logging'

**Comment by kseltar** [comment]
/opt/gateone/gateone.py keep call error
same errors in debian testing 20160120 (python2.7 3.4 {python-tornado  4.2.1})
please try to check n replace for the modern sys call
service gateone start no show error but remember that 2014+ OS have systemd, init.d may not run fine
