### ISSUE TITLE
gateone.py error

### ISSUE THREAD

**Issue by ghost** [liftoff/GateOne#233]
Hi,

I keep getting below error while running /opt/gateone/gateone.py

Traceback (most recent call last):
  File "/opt/gateone/gateone.py", line 289, in <module>
    tornado.options.enable_pretty_logging()
AttributeError: 'module' object has no attribute 'enable_pretty_logging'

My Python version is 
# which python

/usr/local/bin/python
# python -V

Python 2.7.3

Also I installed tornado v 2.4-1 rpm using --nodeps
# rpm -qa | grep tornado

tornado-2.4-1

**Comment by suntao789** [comment]
**verison info:**
Python 2.7.5 (default, Aug  7 2015, 08:58:15) 
tornado-4.3 
GateOne-1.1 

**steps:**
LFG1000127169:/opt/gateone # python gateone.py 
Traceback (most recent call last):
  File "gateone.py", line 289, in <module>
    tornado.options.enable_pretty_logging()
AttributeError: 'module' object has no attribute 'enable_pretty_logging'
LFG1000127169:/opt/gateone # 

this bug stil exist

**Comment by jfhc** [comment]
`
ubuntu@ip:/opt/gateone$ python -V
Python 2.7.11 :: Anaconda 4.0.0 (64-bit)
ubuntu@ip:/opt/gateone$ python -c "import tornado; print(tornado.version)"
4.3
ubuntu@ip:/opt/gateone$ ./gateone.py
Traceback (most recent call last):
  File "./gateone.py", line 289, in <module>
    tornado.options.enable_pretty_logging()
AttributeError: 'module' object has no attribute 'enable_pretty_logging'
`
This is with GateOne 1.1 installed from gateone_1.1-1_all.deb

Would love to have a solution that didn't require 'version gymnastics' :-)

**Comment by ghost** [comment]
Guys, we are in 2019 and I still have the same issue...

root@ip-10-2-224-94:/opt/gateone$ ./gateone.py 
Traceback (most recent call last):
  File "./gateone.py", line 289, in <module>
    tornado.options.enable_pretty_logging()
AttributeError: module 'tornado.options' has no attribute 'enable_pretty_logging'
