### ISSUE TITLE
GateOne always connects to existing terminal in embedded mode

### ISSUE THREAD

**Issue by JohnSundarrajJSR** [liftoff/GateOne#250]
Hi Dan, as you know that i'm doing some R&D on building plugin for GateOne's terminal app. I'm trying to manipulate gateone's session data in my php code. Now I can able to load and exit Terminal successfully with my php code.

Whenever i pass autoconnect ssh url for first time using GateOne.init(), my terminal gets connected with it and within the sessions directory i can see a shell script named 'ssh:1:user@server'. Note that i'm running everything in embedded mode.

My problem is when i accidentially close the browser, and try to load a new terminal with the same autoconnect ssh url, my terminal gets connected to the old ssh script 'ssh:1:user@server' and not launching a new ssh connection. Also the autoconnect url gets populated but no use with that and looks ugly.

Is there any way to destroy the old ssh connection i.e 'ssh:1:user@server' and attach a new fresh ssh connection with my loaded terminal. The terminal number will always be 1, because i'm in embedded mode.

Please suggest me a programmatic way to accomplish this. I'm constantly reading code and have already tried some few idea's using GateOne's API but no luck till now.

Thanks in advance...

**Comment by ypdai** [comment]
i set "0" for session_timeout. its not working too...
but, i try other method do it:

```
$ vim template/index.html
GateOne.init({% raw js_init %});
var prefix = GateOne.prefs.prefix;
var workspace = localStorage[prefix+'selectedWorkspace'];
GateOne.Visual.closeWorkspace(workspace);
```
and modify static/gateone.js 3997 line:

```
$ vim static/gateone.js
if(go.ws && go.ws.readyState == 1)  // line 3997
```

in my env is worked. THX
