### ISSUE TITLE
Gateone embedded mode problem with scrolling

### ISSUE THREAD

**Issue by aryamazaheri** [liftoff/GateOne#360]
Hi there,
I have embedded GateOne into a sample web page. Due to the length of the text above the GateOne div, the page scrolls. So, I have to scroll down the page to see the GateOne screen properly. But, everytime I try to type a character into the GateOne, the web page jumps up to the top. And I have to scroll down manually again. It's really annoying.
Do you have any clue why this happen?

Thanks,

**Comment by Logicman111** [comment]
apparently not...

**Comment by Logicman111** [comment]
Maybe this line in gateone.js:
4528: tempTextArea = u.createElement('textarea', {'style': {'left': '-999999px', 'top': '-999999px'}});
for this one:
tempTextArea = u.createElement('textarea', {'style': {'left': 'null', 'top': '0px'}});

**Comment by liftoff** [comment]
Why can't you upgrade?  1.1 is old and pretty broken at this point.

Anyway, if you apply the change suggested by @Logicman111 that will likely correct the issue but I can't be 100% sure since the way the page rendered in 1.1 is very different from how it works in the latest code.
