### ISSUE TITLE
Multiple consoles in one page

### ISSUE THREAD

**Issue by fringeadmin** [liftoff/GateOne#361]
I'm trying to open multiple GateOne instances in a single page so that I can run them in my own tabs instead of browser tabs. Unfortunately what's happening is that instead of two distinct instances of GateOne opening, one div gets ignored and the other gets filled with the contents that should have gone to the first. I need to add tabs dynamically so I can't just run multiple GateOne processes or something like that.

I've tried multiple things to get this to work. My latest iteration is:

  GateOne.init({url: "https://localhost/?location=term1",
                autoConnectURL: 'ssh://me@localhost:22',
                rowAdjust: 1,
                goDiv: "#gateone1"});
  GateOne.init({url: "https://localhost/?location=term2",
                autoConnectURL: 'ssh://me@remotehost:22',
                rowAdjust: 1,
                goDiv: "#gateone2"});

I saw in a previous issue where mentioned a plan to add syntax like:

Go1 = new GateOne();

But that doesn't work and just gives me an error when I try to call Go1.init:

Uncaught TypeError: Object [object Object] has no method 'init'

Is it possible to run multiple instances on one page and generate them dynamically?

**Comment by sizeoftank** [comment]
@liftoff 
I call  `GateOne.Terminal.newTerminal(null, {"command": "some_command"}, "#gateone_tab1")`  insert terminals in my page, but the terminal input is invalid.

**Comment by liu351** [comment]
@sizeoftank were you able to get around the invalid terminal input issue? I am facing that as well when I have two gateone terminals and tried the embedded setting.
