### ISSUE TITLE
hello_embeded_world can not embed gateone

### ISSUE THREAD

**Issue by teiyaki** [liftoff/GateOne#459]
Hi, I tried run ./hello_embeded_world.py, but no reaction after the "Go!" button is clicked.
My chrome debug console had a error:WebSocket connection to 'wss://my-gateone-server:10443/ws' failed: Error during WebSocket handshake: Unexpected response code: 403 
Why? Please help me.

Gate One:
        Version: 1.2.0 (20140802120917)
Installed Applications:
        Terminal Version: 1.2

ps: I also tried gateone without ssl, but error message is  "WebSocket connection to 'ws://my-gateone-server:1080/ws' failed: Error during WebSocket handshake: Unexpected response code: 403"

Thanks a lot!

**Comment by shahks** [comment]
hi PhunkMaster,

How did you solve this issue? I have edited config file and added ["*"] to it. But still when I do # gateone --logging=debug I get
Connections to this server will be allowed from the following origins: 'localhost:10443 127.0.0.1:10443 127.0.1.1:1044
but I can;t get a * here

**Comment by liftoff** [comment]
Hmm...  Can you paste your config?  I just need the 'origins' setting from 10server.conf and the contents of your 20authentication.conf (and any other custom .conf files you may have created).  Make sure to remove your secret key though (unless you don't care; you're just testing).

**Comment by shahks** [comment]
I am trying basic embedding.
my program(abc.html):

<html>
<head>
	<title>Console</title>
	<script src="GateOne/gateone/tests/hello_embedded/static/gateone.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
</head>
<body>
  <div style="position: relative; width: 100px; height: 75px;">
    <div id="gateone"></div>
  </div>
  <script>
    window.onload = function() {
      GateOne.init({url: 'https://localhost:10443'},{auth:'none'});
    }
  </script>
</body>
</html>

10server.conf
// This is Gate One's main settings file.
{
    // "gateone" server-wide settings fall under "*"
    "*": {
        "gateone": { // These settings apply to all of Gate One
            "address": "",
            "ca_certs": null,
            "cache_dir": "/tmp/gateone_cache",
            "certificate": "/etc/gateone/ssl/certificate.pem",
            "cookie_secret": "OGY5YmY5MzVkMjU1NDk0MmI1NjFlODFkMzUwNDdlNWM5Y",
            "debug": false,
            "disable_ssl": false,
            "embedded": false,
            "enable_unix_socket": false,
            "gid": "0",
            "https_redirect": false,
            "js_init": "",
            "keyfile": "/etc/gateone/ssl/keyfile.pem",
            "locale": "en_US",
            "log_file_max_size": 100000000,
            "log_file_num_backups": 10,
            "log_file_prefix": "/var/log/gateone/gateone.log",
            "log_to_stderr": null,
            "logging": "info",
            "multiprocessing_workers": null,
            "origins": ['*'],   //["*", ""localhost", "127.0.0.1", "Kunal", "127.0.1.1"],
            "pid_file": "/var/run/gateone.pid",
            "port": 443,
            "session_dir": "/tmp/gateone",
            "session_timeout": "5d",
            "syslog_facility": "daemon",
            "uid": "0",
            "unix_socket_mode": "0600",
            "unix_socket_path": "/tmp/gateone.sock",
            "url_prefix": "/",
            "user_dir": "/var/lib/gateone/users",
            "user_logs_max_age": "30d"
        }
    }
}

20authentication.conf:

// This is Gate One's authentication settings file.
{
    // "gateone" server-wide settings fall under "*"
    "*": {
        "gateone": { // These settings apply to all of Gate One
            "api_timestamp_window": "30s",
            "auth": "none",
            "pam_realm": "Kunal",
            "pam_service": "login",
            "ssl_auth": "none",
            "sso_keytab": null,
            "sso_realm": null,
            "sso_service": "HTTP"
        }
    }
}

On starting the server:
[I 150609 15:20:57 server:4172] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.html)
[I 150609 15:20:57 server:4181] Imported applications: Terminal
[I 150609 15:20:57 server:4333] Version: 1.2.0 (20150402170713)
[I 150609 15:20:57 server:4334] Tornado version 4.2
[I 150609 15:20:57 server:4354] Connections to this server will be allowed from the following origins: 'localhost:10443 127.0.0.1:10443 Kunal:10443 127.0.1.1:10443'
[I 150609 15:20:57 server:3671] No authentication method configured. All users will be ANONYMOUS
[I 150609 15:20:57 server:3752] Loaded global plugins: gateone.plugins.help, gateone.plugins.editor
[I 150609 15:20:57 server:4484] Listening on https://*:10443/
[I 150609 15:20:57 server:4537] Process running with pid 416

I have named my file as abc.html. When I open my file in browser- google chrome (dbl click the file), 
the information displayed on the page is:
Attempting to connect to the Gate One server...

and the error in console is:
WebSocket connection to 'wss://localhost:10443/ws' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by liftoff** [comment]
Well your origins setting is incorrect:

    "origins": [''],

You want that to be:

    "origins": ["*"],

Note that the .conf file format (which is JSON) needs double-quotes for values.  Single quotes won't work.

**Comment by shahks** [comment]
I did the same thing with double quotes. Still the same error.

**Comment by shahks** [comment]
[E 150611 10:08:21 server:1566] Origin check failed for: http://localhost
[W 150611 10:08:21 web:1908] 403 GET /ws (127.0.0.1) 4.31ms
[I 150611 10:08:23 server:1797] {"ip_address": "127.0.0.1", "location": "default", "upn": "ANONYMOUS"} WebSocket Latency: 0ms

I get this error in the terminal.

**Comment by longkx** [comment]
this issue perfectly solved my bugs,thanks a lot!
