### ISSUE TITLE
gateone Telnet is not working

### ISSUE THREAD

**Issue by bentech4u** [liftoff/GateOne#489]
i have working gateone.

i created bookmark like below

telnet://user@hostname:23

and it's not working.

even if i pass https://gateone/?telnet=telnet://user@hostname:23 also not working

please help me to fix this issue

**Comment by Id2ndR** [comment]
I got the trouble with docker official container.
The solution was to install telnet package in the system. In case of a docker container: sudo docker exec -t gateone /usr/bin/apt-get install telnet

**Comment by liftoff** [comment]
@Id2ndR Thanks for that!  I'll have a fix for the docker container pushed later today.

**Comment by liftoff** [comment]
Did my Dockerfile fix work?  It should automatically include telnet now--just looking for a confirmation.

**Comment by Id2ndR** [comment]
I confirm that it does work. I just needed to remove the image that didn't update automatically: sudo docker rmi liftoff/gateone

**Comment by liftoff** [comment]
Excellent.  I'm going to close out this ticket then.
