### ISSUE TITLE
Missing 1.2 Documentation

### ISSUE THREAD

**Issue by stangri** [liftoff/GateOne#492]
The old (1.1) documentation (while serving as some point of reference) is obsolete -- any chance Liftoff could publish the proper documentation for 1.2?

**Comment by hackstoic** [comment]
visit this url http://180.151.228.58/GateOne/gateone/docs/html/index.html to get newer version of docs

**Comment by stangri** [comment]
1.2.0 Documentation has been published at https://liftoff.github.io/GateOne/.
