### ISSUE TITLE
Logviewer can't convert .golog to .html?

### ISSUE THREAD

**Issue by huimeizhex** [liftoff/GateOne#502]
./logviewer.py --html 20150228150917028429-127.0.0.1.golog

**Comment by liftoff** [comment]
Hmm...  Strange that doesn't work.  It's supposed to.  In the mean time you can use the gateone command like so to perform the same function:

    gateone termlog --html 20150228150917028429-127.0.0.1.golog

I'll fix it though. Definitely a bug.

**Comment by huimeizhex** [comment]
#!/usr/bin/env python
# coding=utf-8
from gateone.applications.terminal.logviewer import main 


if __name__ == '__main__':
    main()

This can convert golog to html.

**Comment by liftoff** [comment]
I just pushed a fix that should correct this issue.  Can you grab the latest code and give it a try?

**Comment by huimeizhex** [comment]
OK

**Comment by huimeizhex** [comment]
It works

**Comment by liftoff** [comment]
Great.  I'm going to close this issue.
