### ISSUE TITLE
Websocket: Uncaught Exception (download from git)

### ISSUE THREAD

**Issue by mmattel** [liftoff/GateOne#510]
Ubuntu 14.04, Python 2.7

I downloaded and installed gateone from git yesterday (gladfully keeping a working security copy of gateone from June/July last year) and have seen that gateone still does not work because it responds with an error message: Uncaught exception in /gateone/ws.
Please see the log below from gateone.

If I install the old version, it works.

This also references to: #466 (Uncaught exception in /ws)

[I 150316 13:00:25 web:1856] 200 GET /gateone/static/favicon.ico (127.0.0.1) 0.72ms
[I 150316 13:00:30 app_terminal:265] Active Terminal Plugins: bookmarks, convenience, example, html, logging, notice, playback, ssh
[E 150316 13:00:30 websocket:319] Uncaught exception in /gateone/ws
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-3.2.2-py2.7-linux-x86_64.egg/tornado/websocket.py", line 316, in wrapper
        return callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 1600, in open
        logging.debug("open() origin: %s" % self.origin)
    AttributeError: 'ApplicationWebSocket' object has no attribute 'origin'
[I 150316 13:00:30 server:1766] WebSocket closed (xxxx@xxxxxxx 127.0.0.1).
[I 150316 13:00:30 server:677] All user sessions have terminated.

**Comment by Logicman111** [comment]
I read that the latest version (1.2) of Gateone require Tornado 4.1.

**Comment by mmattel** [comment]
This is correct. I have overseen that. I installed Tornado 4.1 and afterwards Gateone, now it works.
Would be great that this version dependency is checked and in case of a missmatch stop installing and print a message...

**Comment by liftoff** [comment]
@mmattel The next commit will include a fix that ensures Tornado is 4.0+.

**Comment by mmattel** [comment]
Thanks, this will help reducing unneccesary issue creation (including the one I did :-) )
