### ISSUE TITLE
Nginx as reverse proxy

### ISSUE THREAD

**Issue by zoic21** [liftoff/GateOne#518]
Hi,

I can not use nginx as reverse proxy with gateone, I get this error : 
Uncaught Failed to load GateOne.SSH due to missing dependencies: GateOne.Bookmarks,GateOne.Terminal,GateOne.Terminal.Input,GateOne.Editor

Without nginx it's ok, here my conf : 
    location / {
               proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_redirect off;
                proxy_pass http://localhost:10443;
        }

And gateone : 

// This is Gate One's main settings file.
{
    // "gateone" server-wide settings fall under "*"
    "*": {
        "gateone": { // These settings apply to all of Gate One
            "address": "",
            "ca_certs": null,
            "cache_dir": "/tmp/gateone_cache",
            "certificate": "/etc/gateone/ssl/certificate.pem",
            "cookie_secret": "ZmQzMmUxZjE4NmJkNDQ0NDlkMzk1OGQzZjZkYmM5NDZjM",
            "debug": false,
            "disable_ssl": true,
            "embedded": true,
            "enable_unix_socket": false,
            "gid": "0",
            "https_redirect": false,
            "js_init": "",
            "keyfile": "/etc/gateone/ssl/keyfile.pem",
            "locale": "fr_FR",
            "log_file_max_size": 100000000,
            "log_file_num_backups": 10,
            "log_file_prefix": "/var/log/gateone/gateone.log",
            "log_to_stderr": null,
            "logging": "info",
            "multiprocessing_workers": null,
            "origins": ["localhost", "127.0.0.1","xxxxxxxxx","xxxxxxxxxxx","xxxxxxxx"],
            "pid_file": "/var/run/gateone.pid",
            "port": 10443,
            "session_dir": "/tmp/gateone",
            "session_timeout": "5d",
            "syslog_facility": "daemon",
            "uid": "0",
            "unix_socket_path": "/tmp/gateone.sock",
            "url_prefix": "/",
            "user_dir": "/var/lib/gateone/users",
            "user_logs_max_age": "30d"
        }
    }
}

When  check network on google chrome I see ws request in pending with "101 Switching Protocols".

I can not see any error on gateone console.

Information : 
system : ubuntu 14.04
gateone : 1.2
nginx : 1.4.6

Thank in adance

**Comment by phealy** [comment]
I use this config (with my prefix set to /ssh in gateone's config):

        location /ssh/ws {
            proxy_pass http://127.0.0.1:4283/ssh/ws;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /ssh {
            proxy_pass http://127.0.0.1:4283/ssh;
            proxy_buffering off;
        }

**Comment by zoic21** [comment]
i tried with that and same error : 
server {
        listen      80 ;
        client_max_body_size 16M;
        error_page  497  https://$host$request_uri;

        access_log off;
        error_log /var/log/vhosts/jeedom.fr/gateone.xxxxxx.fr.error crit;

        server_name gateone.xxxxxxx.fr;

        location /ws {
            proxy_pass http://127.0.0.1:10443/ws;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

         location / {
                proxy_pass http://127.0.0.1:10443;
                proxy_buffering off;
        }
}

**Comment by zoic21** [comment]
I find something : gateone + nginx proxy work find on firefox but not on chrome. Gateone with chrome and without nginx don't work. So for me gateone don't work on chrome

**Comment by geek85** [comment]
I just test with chrome version 41.0.2272.87 m (64-bit) and GateOne behind a Nginx reverse proxy and it's working as fine as with Firefox 37.
my nginx conf:
```nginx
# --- gateone ---
        location  /gateone/ {
            proxy_pass_header   Server;
            proxy_redirect      off;
            proxy_pass          http://127.0.0.1:1443;
            proxy_http_version  1.1;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection "upgrade";
            proxy_read_timeout  86400;
        }
```

**Comment by zoic21** [comment]
It's no a certificat issue, I test with version 2ddbd05a5344d9e821e7765652648fd8e5cc2bab and it's work

**Comment by BennyLi** [comment]
As this is still open: I have a similiar problem regarding the Nginx proxy. I have setup GateOne from GitHub master branch a34f7e0a92 with Python 2.7.3 and Tornado 4.0.2 on a Raspberry Pi. Accessing it via the LAN IP:Port/gateone it's working fine. But trying to access it via my domain from external with Nginx as Proxy it does not work (Grey Screen, /gateone/ws pending).

Screenshot from Chrome Devloper Tools Network Tab:
![image](https://cloud.githubusercontent.com/assets/5690260/7978364/bc917d86-0a94-11e5-95c2-3984daf6bd4b.png)

Nginx location config:
```
location ^~ /gateone {
  root /usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg;

  try_files $uri $uri/index.html $uri.html @gateone;
}

location @gateone {
  proxy_pass http://localhost:8021;

  proxy_redirect off;
  proxy_pass_header Server;
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $http_address;
  proxy_set_header X-Scheme $scheme;
    
  # Support WebSockets
  # see http://nginx.org/en/docs/http/websocket.html
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
}
```

GateOne 10server.conf:
```
{
    // "gateone" server-wide settings fall under "*"
    "*": {
        "gateone": { // These settings apply to all of Gate One
            "address": "",
            "ca_certs": null,
            "cache_dir": "/tmp/gateone_cache",
            "certificate": "/etc/nginx/certs/server.chained.pem",
            "cookie_secret": "MWQ5NTA4MWE3ODMyNGY3OWJiY2QxODQyZjY0Y2I1NGE1Z",
            "debug": false,
            "disable_ssl": true,
            "embedded": false,
            "enable_unix_socket": true,
            "gid": "33", //www-data group
            "https_redirect": false,
            "js_init": "",
            "keyfile": "/etc/nginx/certs/server.key.pem",
            "locale": "en_US",
            "log_file_max_size": 100000000,
            "log_file_num_backups": 10,
            "log_file_prefix": "/var/log/gateone/gateone.log",
            "log_to_stderr": null,
            "logging": "info",
            "multiprocessing_workers": null,
            "origins": ["localhost", "127.0.0.1", "benny-li.de", "127.0.1.1"],
            "pid_file": "/var/run/gateone.pid",
            "port": 8021,
            "session_dir": "/tmp/gateone",
            "session_timeout": "12h",
            "syslog_facility": "daemon",
            "uid": "0",
            "unix_socket_mode": "0660",
            "unix_socket_path": "/tmp/gateone.sock",
            "url_prefix": "/gateone/",
            "user_dir": "/var/lib/gateone/users",
            "user_logs_max_age": "30d"
        }
    }
}
```

GateOne Log:
```
[W 150604 08:48:03 app_terminal:2736] dtach command not found.  dtach support has been disabled.
[I 150604 08:48:04 server:4172] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.htm
l)
[I 150604 08:48:04 server:4181] Imported applications: Terminal
[I 150604 08:48:04 server:4333] Version: 1.2.0 (20150402170713)
[I 150604 08:48:04 server:4334] Tornado version 4.0.2
[I 150604 08:48:04 server:4354] Connections to this server will be allowed from the following orig
ins: 'localhost 127.0.0.1 benny-li.de 127.0.1.1'
[I 150604 08:48:04 server:3671] No authentication method configured. All users will be ANONYMOUS
[I 150604 08:48:04 server:3752] Loaded global plugins: gateone.plugins.editor, gateone.plugins.hel
p
[I 150604 08:48:04 server:4449] Listening on Unix socket '/tmp/gateone.sock' (0660)
[I 150604 08:48:04 server:4484] Listening on http://*:8021/
[I 150604 08:48:04 server:4537] Process running with pid 5287
[I 150604 08:48:09 web:1811] 200 GET /gateone/ (127.0.0.1) 128.41ms
[I 150604 08:48:09 web:1811] 304 GET /gateone/auth?check=True (127.0.0.1) 14.64ms
[I 150604 08:48:09 app_terminal:265] Active Terminal Plugins: bookmarks, convenience, example, htm
l, logging, notice, playback, ssh
[I 150604 08:48:09 server:1633] WebSocket opened (ANONYMOUS 127.0.0.1) via origin benny-li.de.
[I 150604 08:48:09 server:2992] {"ip_address": "127.0.0.1", "upn": "ANONYMOUS"} Sync check: gateon
e_utils_extra.js
[I 150604 08:48:09 server:2992] {"ip_address": "127.0.0.1", "upn": "ANONYMOUS"} Sync check: gateon
e_visual_extra.js
[I 150604 08:48:09 server:2992] {"ip_address": "127.0.0.1", "upn": "ANONYMOUS"} Sync check: gateon
e_input.js
[I 150604 08:48:09 server:2992] {"ip_address": "127.0.0.1", "upn": "ANONYMOUS"} Sync check: gateon
e_misc.js
[I 150604 08:48:09 server:2992] {"ip_address": "127.0.0.1", "upn": "ANONYMOUS"} Sync check: doT.js
```

Any suggestions?

**Comment by BennyLi** [comment]
Ok. I guess I find my fault. The Nginx delivered with the Raspbian OS packages is quite old. `nginx -v` outputs `nginx version: nginx/1.2.1`. And this is the problem. WebSocket support was introduced with version 1.3: http://nginx.com/news/nginx-websockets/

I will try to upgrade Nginx and give some response after.
