### ISSUE TITLE
Nothing in application block

### ISSUE THREAD

**Issue by Kingyo** [liftoff/GateOne#524]
Hello,

I just install GateOne for the first time on my Debian 7 and when I start it, go on it with my browser (firefox 24.0) I see nothing where the applications are normally.
I've tried to Sign out but that did nothing.
In console (firefox) I got this : 
[12:06:41,330] uncaught exception: Failed to load GateOne.SSH due to missing dependencies: GateOne.Bookmarks,GateOne.Terminal,GateOne.Terminal.Input,GateOne.Editor

I searched here and in the documentation but found nothing that can help me ...

Thank you for help !

**Comment by qistoph** [comment]
Just had the same issue on Debian 7 (wheezy).

**Comment by natheran** [comment]
the same here... Debian 7
It works on Chrome but not on IE11.

**Comment by jjuu** [comment]
The same issue, not work on IE11

**Comment by liftoff** [comment]
I'm currently working on IE11 compatibility.  Man IE is such a pain in the ass to troubleshoot!

**Comment by thrbowl** [comment]
Are all IE browsers version not be supported now?
