### ISSUE TITLE
More usage file config "ssh"

### ISSUE THREAD

**Issue by belette** [liftoff/GateOne#543]
Hello,

Congratulation for the project ;)

It's possible remove option ["-p", str(port) and "-l", user,] in file "ssh_connect.py" for usage the parameter settings in the SSH config?

Or testing if options "port/user" are defined (example : http://IP_PORT_GATEONE/?ssh=ssh://user@server:port) in ssh command line, if not define (example : http://IP_PORT_GATEONE/?ssh=ssh://server) launch command line without option "user/port"?

regards,

**Comment by liftoff** [comment]
Interesting question...  The only way I can think of to make this work is to check the user's SSH configuration file before passing the parameters to the ssh command.  That will necessitate writing a parser for that file.

...unless you have a better idea?
