### ISSUE TITLE
unix_listener: "/opt/GateOne/GateOne-master/sessions/MzAyYTMxNDUwNjYwNDlkMjlhM2EwMDYzNjM2YjQ0MGMzM/bGJGBJJV.CvFxtgaR6nSLRs07" too long for Unix domain socket

### ISSUE THREAD

**Issue by nephaste** [liftoff/GateOne#548]
made a Qnap QPKG, all runs fine expect i cant log after credential accept got an error :

unix_listener: "/opt/GateOne/GateOne-master/sessions/MzAyYTMxNDUwNjYwNDlkMjlhM2EwMDYzNjM2YjQ0MGMzM/bGJGBJJV.CvFxtgaR6nSLRs07" too long for Unix domain socket

any idea ?

i tried to export 

export UNIX_PATH_MAX=108

but keep in error

thanks a lot...

**Comment by nephaste** [comment]
seems the Path is too long, i make it shorter and it works ;)

**Comment by dgkncelik** [comment]
Could you please share how did you make this change :) ?

**Comment by JFanGitHub** [comment]
I met this problem as well, how do you figure it out

**Comment by cam-mobo** [comment]
I also had this problem, and would like to know how you made the path shorter.

**Comment by csharpemcee** [comment]
bro stop hiding information tell us how to fix it!

**Comment by csharpemcee** [comment]
@nephaste
