### ISSUE TITLE
FileNotFoundError: `python34.zip` in python 3.4 + tornado 4.2

### ISSUE THREAD

**Issue by ahmed-taj** [liftoff/GateOne#555]
Hey, there

I'm trying to install GateOne (from master branch) in Ubuntu + python 3.4.3 + tornado 4.2, but I always got this message :

	test@test-PC:~/Desktop/GateOne-master$ sudo python3 setup.py build
	running build
	running build_py
	file gateone.py (for module gateone) not found
	file gateone.py (for module gateone) not found
	Traceback (most recent call last):
	  File "setup.py", line 337, in <module>
		files = os.listdir(path)
	FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python34.zip'

Any help ?

**Comment by liftoff** [comment]
Well, you shouldn't need to run "build" if you plan to install Gate One.  Just run `sudo python3 setup.py install`.

Having said that, I have no idea why you're getting this error.  I'm running Ubuntu 15.04 and can install Gate One from scratch without this issue.  Are you still encountering this?

**Comment by ahmed-taj** [comment]
Ok, I got it

Thanks
