### ISSUE TITLE
"Edit Saved Hosts doesn't actually save

### ISSUE THREAD

**Issue by hkelly** [liftoff/GateOne#562]
When modifying "Edit Saved Hosts" and hitting "save", it doesn't actually save and if you reopen the popup, you can see that it is all still there.

**Comment by liftoff** [comment]
Confirmed.  For whatever reason the client isn't sending the form data via the XHR request.  I'm going to re-write that code to use a WebSocket action.  It should simplify things considerably and make it more reliable.

**Comment by hkelly** [comment]
This is also true for the preferences, might be the same issue. If you change the font size to 200% and hit save, it changes, but refreshing the page loses your change and it goes back to 100%. Changing the font size also has to change on the page.

**Comment by hkelly** [comment]
This isn't a major bug though, it isn't blocking us from using this.

**Comment by liftoff** [comment]
Client prefs are saved in localstorage.  If that's not working it's a separate bug.  I'll investigate.

**Comment by liftoff** [comment]
I pushed a commit yesterday that should have corrected this issue.  Can you grab the latest code and give it a try?

**Comment by hkelly** [comment]
That fixed it thanks!
