### ISSUE TITLE
Issues with latest firefox: no backspace & no <TAB>

### ISSUE THREAD

**Issue by piejanssens** [liftoff/GateOne#564]
Can't use tab to complete commands, can't use packspace or delete to correct input and can't use arrows to move cursor.
In addtion it seems that the layout of the initial logon screen (where you select host/port) is put too high (a little off screen).

**Comment by dramixx** [comment]
I have the same problem since the end of 2015, like you.
Backspace key, arrows, tab, ... all these keys don't work anymore.
