### ISSUE TITLE
server.crt Permisison denied !

### ISSUE THREAD

**Issue by dramixx** [liftoff/GateOne#609]
Hi, 

I have a Synology DS716+ and when i try to launch gateone, nothing happens and gateone is not launched.

So i try to run /var/packages/gateone/start-stop-status start and i get : 
```
cp: cannot stat ‘/usr/syno/etc/ssl/ssl.crt/server.crt’: Permission denied
cp: cannot stat ‘/usr/syno/etc/ssl/ssl.key/server.key’: Permission denied
chown: changing ownership of ‘/usr/local/gateone/ssl/certificate.pem’: Operation not permitted
chown: changing ownership of ‘/usr/local/gateone/ssl/keyfile.pem’: Operation not permitted
```

What I have to change to be able to launch gateone ?

Thx a lot,

**Comment by liftoff** [comment]
It sounds like Gate One was installed (and meant to run as) root but you're running it as a different user.  Configure Gate One to start as root *or* just change the file ownership/permissions of the problematic files (e.g. /usr/syno/etc/ssl/ssl/*) so that Gate One can read them.

**Comment by dramixx** [comment]
OK thanks it works :) !
