### ISSUE TITLE
GateOne doesn't use full screen width

### ISSUE THREAD

**Issue by gravufo** [liftoff/GateOne#619]
Using latest gateone docker, the text appearing in the console does not use the full width.

Here are my specs:
Docker version 1.10.3, build 20f81dd
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
Browser: Chrome 51.0.2704.103 m

Here is a sample of a `docker ps -a` command output:
![Screenshot](https://cloud.githubusercontent.com/assets/475807/16473202/1d5c5036-3e39-11e6-8015-5091eb7c9251.png)

**Comment by viperidae** [comment]
I found resizing the browser window after logging in corrects the screen width issues.

**Comment by gsl0610** [comment]
Hi, have you fixed this issue?

**Comment by gsl0610** [comment]
I encounter the same issue, when open the gateone for the first time, only half screen is shown.

**Comment by gravufo** [comment]
Closing old issue, probably not relevant anymore since this project is abandoned.
