### ISSUE TITLE
Failed to load resource: net:: ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by skywalker45** [liftoff/GateOne#672]
Hi, 

Straight to the point, i am working on a project that provides a textarea over a web interface  where people can write their code, compile it and get an output. Kinda like [https://www.tutorialspoint.com/compile_java8_online.php]. 

I am trying to use GateOne as the terminal. While following the tutorial, everything seemed to be relatively straight forward until i try to embed GateOne in a div tag. 
I haven't exactly worked with SSL before but i have read about it. This project is not in production rather development stage, so i disable SSL in the 10server.conf, set embed to true and ran the webpage with the link to the gateone.js and the onload function. I don't get any error, but i also don't see Gateone in the div. When i check javascript console, i see Failed to load resource: net:: ERR_SSL_PROTOCOL_ERROR which makes GateOne undefined. 

Is there an advisable fix for this, or anything i can try. I am currently looking up ways to hanle SSL protocol error, but i haven't been able to apply that to Gateone. Any help would be appreciated. If you would like to see the codes, please just ask and i'll paste them

**Comment by skywalker45** [comment]
Haha, works now... i was working with nginx server and i tried using a proxy and i got it all messed up. But you don't need to run it as a proxy on nginx for it to work. I just didn't know enough about SSL, so i got the configuration completely wrong..

**Comment by lizwikagiso** [comment]
Hi skywalker45,
How you managed to solve the issue? I got the same error...the cert is installed i can see it on the url but on the console its showing this error. 
Failed to load resource: net:: ERR_SSL_PROTOCOL_ERROR
