### ISSUE TITLE
Gateone not reading config file

### ISSUE THREAD

**Issue by tslytsly** [liftoff/GateOne#675]
Hi,
Bit of an odd one.

I have installed on Ubuntu 16 using the setup.py script.

I modified the `/etc/gateone/conf.d/10server.conf` file with my settings. The main change here is that I am using a different port from 443 for access.

If I manually run `gateone` it loads from the settings file in `/home/<user>/.gateone/conf.d/10server.conf`. (Which is fine for testing, I copied the conf file to both locations)
If I do `sudo gateone` I get this error:
```
[I 170823 10:26:00 server:4491] Listening on https://*:443/
[E 170823 10:26:00 server:4553] Could not listen on 0.0.0.0:443 (address:port is
 already in use by another application).
```
This is because I already have something running on 443, hence the need to change the port.
It's almost like it's not reading the config file.
I get the same error if I start the service.

If I do `sudo gateone --settings_dir=/etc/gateone/conf.d/` I get the same error again.
If I specify the conf file in my home dir it works... I don't know why,

I have compared the conf files side by side and they are identical.

Any help appreciated.

**Comment by tslytsly** [comment]
any thoughts from anyone?

**Comment by paulcst** [comment]
i think you could use “killall -9 gateone” to kill the process before running new.

**Comment by tslytsly** [comment]
Sorted it.
It was because I backed up the original `10server.conf` file to `old_10server.conf`
I think it was reading my new `10server.conf` file and then reading the old one after and overwriting.
Doh!
