### ISSUE TITLE
ssh: connect to host localhost port 22: Cannot assign requested address

### ISSUE THREAD

**Issue by kargakis** [liftoff/GateOne#679]
Getting this on the terminal when running in a container I built following https://github.com/liftoff/GateOne/blob/master/docker/README.md
```
[Press Shift-F1 for help]

Host/IP or ssh:// URL [localhost]:
Port [22]:
User:
User: kargakis
Connecting to ssh://kargakis@localhost:22

ssh: connect to host localhost port 22: Cannot assign requested address
[Press Enter to close this terminal]
```
No idea what's the issue and I can't see anything obvious in the container log.

**Comment by jkinred** [comment]
When you specify `localhost` as the host to connect to you are specifying the Docker container which GateOne is running in. As there is no SSH daemon running inside the container you receive the error message.

If you just want to connect to something to test GateOne, you should be able to connect to the Docker host.

Get the IP of the Docker host:

```
$ sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' gateone
172.17.0.1
```

Then in GateOne web application:

```
[Press Shift-F1 for help]

Host/IP or ssh:// URL [localhost]: 172.17.0.1
Port [22]:
User: jonathan
Connecting to ssh://jonathan@172.17.0.1:22
<snip>
jonathan@172.17.0.1's password:
jonathan@nomad ~ $
```

Another option is to run a container with an SSH daemon -- (password for `root` is `node` as per [the Dockerfile](https://hub.docker.com/r/ncc0706/alpine-sshd/~/dockerfile/):

```
$ sudo docker run -d --name sshd ncc0706/alpine-sshd
$ sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sshd
172.17.0.3
```

Then in GateOne web application:

```
[Press Shift-F1 for help]
 
Host/IP or ssh:// URL [localhost]: 172.17.0.3
Port [22]:
User: root
Connecting to ssh://root@172.17.0.3:22

root@172.17.0.3's password:
<snip>
3e201f6cbb29:~#

**Comment by 0xmichalis** [comment]
@jkinred thanks for your reply, I haven't actually tried this again but I am going to close this issue as it seems like it's not an issue on gateone's side.
