### ISSUE TITLE
cannot create new terminal

### ISSUE THREAD

**Issue by manulin44** [liftoff/GateOne#75]
when I try to create a new Terminal, I have these messages :

[W 111121 13:23:53 gateone:1633] dtach command not found.  dtach support has been disabled.
[I 111121 13:23:53 gateone:1340] No authentication method configured. All users will be %anonymous
[I 111121 13:23:53 gateone:1373] Loaded plugins: bookmarks, help, logging, playback, ssh
[I 111121 13:23:53 gateone:1697] Listening on https://_:8022/
[W 111121 13:24:05 web:1889] Invalid cookie signature 'eyJnb19zZXNzaW9uIjogIllqUmtORGcyTldNelpUZ3lORFU0WldFeU1HVTNZalZqT0RneE5XRmtZMlEyTyIsICJnb191cG4iOiAiJWFub255bW91cyJ9|1321371333|abb4e7c4bf9d14b8bbf3f1ed5f865a2e2d0c229b'
[I 111121 13:24:05 web:1359] 302 GET / (192.168.0.22) 4.60ms
[I 111121 13:24:05 auth:94] Creating user directory: /volume1/@appstore/gateone/bin/users/%anonymous
[I 111121 13:24:05 web:1359] 302 GET /auth?next=%2F (192.168.0.22) 6.35ms
[I 111121 13:24:05 web:1359] 200 GET / (192.168.0.22) 41.92ms
[I 111121 13:24:05 web:1359] 304 GET /static/gateone.css (192.168.0.22) 2.14ms
[I 111121 13:24:06 web:1359] 304 GET /static/ssh/ssh.js (192.168.0.22) 1.92ms
[I 111121 13:24:06 web:1359] 304 GET /static/gateone.js (192.168.0.22) 1.78ms
[I 111121 13:24:06 web:1359] 304 GET /static/bookmarks/bookmarks.js (192.168.0.22) 1.87ms
[I 111121 13:24:06 web:1359] 304 GET /static/help/help.js (192.168.0.22) 1.86ms
[I 111121 13:24:06 web:1359] 304 GET /static/logging/logging.js (192.168.0.22) 2.02ms
[I 111121 13:24:06 web:1359] 304 GET /static/playback/playback.js (192.168.0.22) 1.91ms
[I 111121 13:24:07 web:1359] 304 GET /style?colors=default&container=gateone&prefix=go_ (192.168.0.22) 53.20ms
[I 111121 13:24:07 web:1359] 304 GET /style?theme=black&container=gateone&prefix=go_ (192.168.0.22) 75.91ms
[I 111121 13:24:08 gateone:707] WebSocket opened (%anonymous).
[E 111121 13:24:15 websocket:173] Uncaught exception in /ws
    Traceback (most recent call last):
      File "/usr/local/python27/lib/python2.7/site-packages/tornado/websocket.py", line 170, in wrapper
        return callback(_args, **kwargs)
      File "./gateone.py", line 728, in on_message
        self.commands[key](value)
      File "./gateone.py", line 960, in new_terminal
        self.refresh_screen(term, True) # Send a fresh screen to the client
      File "./gateone.py", line 1086, in refresh_screen
        term = int(term)
    TypeError: int() argument must be a string or a number, not 'NoneType'
[I 111121 13:24:15 gateone:744] WebSocket closed (%anonymous).
[E 111121 13:24:16 ioloop:410] Exception in callback <tornado.stack_context._StackContextWrapper object at 0xf6eda70c>
    Traceback (most recent call last):
      File "/usr/local/python27/lib/python2.7/site-packages/tornado/ioloop.py", line 396, in _run_callback
        callback()
      File "./gateone.py", line 1086, in refresh_screen
        term = int(term)
    TypeError: int() argument must be a string or a number, not 'NoneType'
[I 111121 13:24:19 gateone:1293] TidyThread MGUwNGE1YjYyNmJjNDY5MWFjY2ExYmU4ZWM4Yjg0YmQwY received quit()...  Killing termio session.
[I 111121 13:24:21 gateone:707] WebSocket opened (%anonymous).

and it is written NaN: New Terminal in my navigator. 

Client side : Firefox 8.0
Server side : python 2.7

**Comment by vijaygalagali20** [comment]
what is reason for this error:
[E 170414 13:26:08 server:1736] {"ip_address": "179.0.0.102", "location": "default", "upn": "ANONYMOUS"} Error in WebSocket action, go:authenticate: 'NoneType' object is not iterable (/usr/local/lib/python2.7/dist-packages/tornado-4.5b2-py2.7-linux-x86_64.egg/tornado/web.py line 887)
